### ISSUE TITLE
Stopped working in messages 

### ISSUE THREAD

**Issue by berlandez** [warpling/Macmoji#24]
typing in an emoji that doesn't appear in shortcuts breaks Macmoji .  
Steps to reproduce:
1. type ":pear:"  in messages on Mac
2. delete pear and then type ":phone:" 
3. delete phone and type ":pear:"     again

**Comment by warpling** [comment]
Interesting… I have noticed weird behavior like this before unfortunately 😞
My theory is that it has to do with the auto-correct system trying to get out of your way when it thinks you're repeatedly trying to correct it.

Closing for now since Macmoji itself isn't involved. Have you checked out [Rocket](http://matthewpalmer.net/rocket/) yet? Might be a more robust solution for you!
